<script setup lang="ts">
const products = [
  { id: 1, name: 'Prada Klasik Emas', description: 'Motif bunga dan sulur emas di atas dasar merah marun. Cocok untuk busana upacara dan kain penghias pelinggih.', material: 'Tenun katun, sepuhan emas', size: '2,5 m × 1,1 m', color: '#6B2A2A', pattern: 'classic' },
  { id: 2, name: 'Prada Patra Punggel', description: 'Motif ukiran patra klasik di atas dasar hitam pekat. Umum dipakai sebagai kain gantung dan penghias altar.', material: 'Tenun katun, sepuhan emas', size: '2 m × 1 m', color: '#1C1912', pattern: 'patra' },
  { id: 3, name: 'Prada Songket Kombinasi', description: 'Perpaduan tenun songket dan sentuhan prada di atas dasar coklat tua. Pilihan istimewa untuk kebaya dan kamen.', material: 'Songket, sepuhan emas', size: '2,3 m × 1,1 m', color: '#4A2E1B', pattern: 'dots' },
]
const rituals = [
  ['♢', 'Sangku Daksina', 'Wadah untuk daksina.'], ['▱', 'Srembeng', 'Keranjang anyaman sesaji.'], ['◯', 'Sangku', 'Wadah untuk menampung tirta.'], ['⊞', 'Sabuk Prada', 'Kain prada pelengkap upacara.'], ['♨', 'Kekasang', 'Kain pelengkap upacara.'],
]
</script>

<template>
  <main id="top">
    <section class="px-6 py-24 max-lg:py-16 max-sm:py-10"><div class="mx-auto grid max-w-screen-xl items-center gap-16 lg:grid-cols-[1.05fr_.95fr]">
      <div><span class="mb-3.5 inline-block text-xs italic uppercase tracking-[.18em] text-gold">Warisan Perajin Bali</span><h1 class="mb-5 font-display text-5xl leading-tight max-lg:text-4xl max-sm:text-3xl">Kain Prada &amp; Perlengkapan Upacara Khas Bali</h1><p class="mb-8 max-w-[46ch] text-brown-700">Kain prada tenun tangan bersepuh emas, disertai perlengkapan upacara pilihan, dibuat oleh perajin di Bali untuk melengkapi setiap persembahan dan perayaan.</p><div class="flex flex-wrap gap-4"><a href="#kain-prada" class="bg-brown-950 px-7 py-3 text-sm text-cream transition hover:bg-brown-700">Lihat Kain Prada</a><NuxtLink to="/catalog" class="border border-gold px-7 py-3 text-sm text-gold transition hover:bg-gold hover:text-white">Lihat Katalog</NuxtLink><a href="#alat-upacara" class="border border-brown-border px-7 py-3 text-sm text-brown-700 transition hover:border-gold hover:text-gold">Lihat Alat Upacara</a></div></div>
      <div class="relative mx-auto w-full max-w-[400px] max-lg:order-first max-sm:hidden"><svg viewBox="0 0 400 480" class="w-full"><defs><pattern id="hero" width="46" height="46" patternUnits="userSpaceOnUse" patternTransform="rotate(18)"><circle cx="23" cy="23" r="1.6" fill="#D9BD8E"/><path d="M23 8L27 20L39 23L27 26L23 38L19 26L7 23L19 20Z" fill="none" stroke="#D9BD8E" opacity=".55"/></pattern></defs><rect width="400" height="480" fill="#3E2A1B"/><rect width="400" height="480" fill="url(#hero)"/><rect x="18" y="18" width="364" height="444" fill="none" stroke="#B8935A"/></svg></div>
    </div></section>
    <section id="kain-prada" class="bg-brown-950 px-6 py-24 text-white max-sm:py-12"><div class="mx-auto max-w-screen-xl"><div class="mb-12 max-w-[60ch]"><span class="mb-3.5 inline-block text-xs italic uppercase tracking-[.18em] text-gold-soft">Koleksi Utama</span><h2 class="mb-4 font-display text-4xl max-sm:text-3xl">Kain Prada</h2><p class="text-text-muted">Prada adalah teknik menyepuh kain dengan serbuk atau lembaran emas, dikerjakan tangan di atas kain tenun. Setiap motif digambar dan disepuh satu per satu, menjadikan tiap lembar kain unik.</p></div><div class="grid gap-8 md:grid-cols-3 max-md:gap-5"> <article v-for="product in products" :key="product.id" class="overflow-hidden border border-brown-border bg-brown-card transition hover:-translate-y-1 hover:border-gold"><svg viewBox="0 0 400 300" class="w-full"><rect width="400" height="300" :fill="product.color"/><pattern :id="product.pattern" width="40" height="40" patternUnits="userSpaceOnUse"><circle cx="20" cy="20" r="1.6" fill="#D9BD8E"/><path d="M20 8L23 18L33 20L23 22L20 32L17 22L7 20L17 18Z" fill="none" stroke="#D9BD8E" opacity=".6"/></pattern><rect width="400" height="300" :fill="`url(#${product.pattern})`"/></svg><div class="p-6"><h3 class="mb-2 font-display text-xl">{{ product.name }}</h3><p class="mb-4 text-sm text-text-muted">{{ product.description }}</p><div class="mb-5 border-t border-brown-border pt-3 text-xs text-gold-soft">Bahan: {{ product.material }}<br>Ukuran: {{ product.size }} (dapat disesuaikan)</div><NuxtLink :to="`/products/${product.id}`" class="inline-block w-full border border-gold px-5 py-2.5 text-center text-xs text-gold-soft hover:bg-gold hover:text-white">Lihat Detail</NuxtLink></div></article></div></div></section>
    <section id="alat-upacara" class="px-6 py-24 max-sm:py-12"><div class="mx-auto max-w-screen-xl"><div class="mb-12"><span class="mb-3.5 inline-block text-xs italic uppercase tracking-[.18em] text-gold">Pelengkap Upacara</span><h2 class="mb-4 font-display text-4xl max-sm:text-3xl">Alat-Alat Bali Lainnya</h2><p class="text-brown-700">Selain kain prada, kami juga menyediakan perlengkapan upacara harian yang dibuat oleh perajin lokal.</p></div><div class="grid grid-cols-2 gap-px border border-gray-light bg-gray-light md:grid-cols-5"> <div v-for="([icon,name,desc]) in rituals" :key="name" class="bg-cream p-8 text-center hover:bg-[#F3EEE3]"><div class="mb-4 text-3xl">{{ icon }}</div><h3 class="mb-2 font-display">{{ name }}</h3><p class="text-xs text-gray">{{ desc }}</p></div></div></div></section>
    <section id="tentang" class="px-6 py-24 max-sm:py-12"><div class="mx-auto grid max-w-screen-xl gap-16 lg:grid-cols-[.9fr_1.1fr]"><div><span class="mb-3.5 inline-block text-xs italic uppercase tracking-[.18em] text-gold">Tentang Kami</span><h2 class="mb-5 font-display text-4xl max-sm:text-3xl">Dikerjakan Tangan, Diwariskan Turun-Temurun</h2><p class="mb-4 text-brown-700">Griya Prada Bali berawal dari sanggar keluarga kecil yang membuat kain prada untuk kebutuhan upacara di desa. Kini kami bekerja sama dengan beberapa perajin di Bali untuk menjaga teknik sepuhan emas tetap dikerjakan dengan cara yang sama seperti dahulu.</p><p class="text-brown-700">Setiap kain dan alat upacara kami buat berdasarkan pesanan, sehingga motif, ukuran, dan jumlah dapat disesuaikan dengan kebutuhan upacara Anda.</p></div><blockquote class="border-l-2 border-gold pl-6 font-display text-2xl leading-relaxed">“Emas di atas kain bukan sekadar hiasan — ia adalah cara kami menghaturkan yang terbaik.”<cite class="mt-3 block font-body text-sm text-gray">— Griya Prada Bali</cite></blockquote></div></section>
  </main>
</template>
